// GENERATED FILE - do not edit by hand.
// Source of truth: mcu-tracker.html  ->  regenerate with: python tools/gen_data.py
//
// All 47 entries in the poster's release order.

enum Status { essential, important, requiredUniverse, upcoming }

extension StatusLabel on Status {
  String get label => switch (this) {
        Status.essential => 'Essential',
        Status.important => 'Important',
        Status.requiredUniverse => 'Required Universe',
        Status.upcoming => 'Upcoming',
      };
}

class Entry {
  const Entry({
    required this.n,
    required this.saga,
    required this.title,
    required this.year,
    required this.status,
    required this.why,
    required this.how,
    this.tag,
  });

  /// Position in the poster's release order, 1-47.
  final int n;

  /// 1 = Infinity Saga, 2 = Multiverse Saga.
  final int saga;

  final String title;
  final String year;
  final Status status;

  /// Why it matters / what you'll learn.
  final String why;

  /// How it connects to the bigger story.
  final String how;

  /// Poster's parenthetical, e.g. 'Series' or 'Fox Universe'.
  final String? tag;
}

const String sagaOneTitle = 'The Infinity Saga · Phases 1–3';
const String sagaTwoTitle = 'The Multiverse Saga · Road to Doomsday';

const List<Entry> entries = <Entry>[
  Entry(
    n: 1,
    saga: 1,
    title: 'Iron Man',
    year: '2008',
    status: Status.essential,
    why: 'Introduces Tony Stark and the beginning of the MCU.',
    how: 'Tony Stark kickstarts the Avengers Initiative.',
  ),
  Entry(
    n: 2,
    saga: 1,
    title: 'The Incredible Hulk',
    year: '2008',
    status: Status.essential,
    why: 'Introduces Bruce Banner, the Hulk, and General Ross.',
    how: 'Hulk\'s story continues and he becomes a core Avenger.',
  ),
  Entry(
    n: 3,
    saga: 1,
    title: 'Iron Man 2',
    year: '2010',
    status: Status.essential,
    why: 'Expands Tony\'s world; introduces Natasha Romanoff and James Rhodes.',
    how: 'Sets up future armor tech, S.H.I.E.L.D. depth, and Thor\'s hammer.',
  ),
  Entry(
    n: 4,
    saga: 1,
    title: 'Thor',
    year: '2011',
    status: Status.essential,
    why: 'Introduces Thor, Loki, Asgard, and the Tesseract.',
    how: 'Thor becomes a key Avenger; Space Stone introduced.',
  ),
  Entry(
    n: 5,
    saga: 1,
    title: 'Captain America: The First Avenger',
    year: '2011',
    status: Status.essential,
    why: 'Steve Rogers\' origin, Super Soldier Serum, and HYDRA.',
    how: 'Sets up Steve\'s role, the Tesseract, and HYDRA\'s persistence.',
  ),
  Entry(
    n: 6,
    saga: 1,
    title: 'Marvel\'s The Avengers',
    year: '2012',
    status: Status.essential,
    why: 'First team-up of Earth\'s Mightiest Heroes against Loki.',
    how: 'Loki\'s invasion establishes the team and teases Thanos.',
  ),
  Entry(
    n: 7,
    saga: 1,
    title: 'Iron Man 3',
    year: '2013',
    status: Status.essential,
    why: 'Tony faces post-New York trauma and Extremis tech.',
    how: 'Drives Tony\'s obsession to build planetary defense (Ultron).',
  ),
  Entry(
    n: 8,
    saga: 1,
    title: 'Thor: The Dark World',
    year: '2013',
    status: Status.essential,
    why: 'Continues Thor\'s story and introduces the Aether.',
    how: 'The Aether is revealed as the Reality Stone.',
  ),
  Entry(
    n: 9,
    saga: 1,
    title: 'Captain America: The Winter Soldier',
    year: '2014',
    status: Status.essential,
    why: 'Steve uncovers HYDRA inside S.H.I.E.L.D. and finds Bucky.',
    how: 'Major turning point that collapses S.H.I.E.L.D. and leads to Civil War.',
  ),
  Entry(
    n: 10,
    saga: 1,
    title: 'Guardians of the Galaxy',
    year: '2014',
    status: Status.essential,
    why: 'Introduces the Guardians team and the cosmic side of the MCU.',
    how: 'Features the Power Stone and Thanos\' first major appearance.',
  ),
  Entry(
    n: 11,
    saga: 1,
    title: 'Avengers: Age of Ultron',
    year: '2015',
    status: Status.essential,
    why: 'Avengers face AI Ultron; Vision and Wanda introduced.',
    how: 'Vision born from Mind Stone; sets up civil tension.',
  ),
  Entry(
    n: 12,
    saga: 1,
    title: 'Ant-Man',
    year: '2015',
    status: Status.important,
    why: 'Introduces Scott Lang, Pym Particles, and the Quantum Realm.',
    how: 'Quantum tech becomes critical in the Endgame time heist.',
  ),
  Entry(
    n: 13,
    saga: 1,
    title: 'Captain America: Civil War',
    year: '2016',
    status: Status.essential,
    why: 'Avengers split over Sokovia Accords; introduces Black Panther and Spidey.',
    how: 'Fractures the team, leaving Earth vulnerable to Thanos.',
  ),
  Entry(
    n: 14,
    saga: 1,
    title: 'Doctor Strange',
    year: '2016',
    status: Status.essential,
    why: 'Introduces sorcery, alternate dimensions, and Stephen Strange.',
    how: 'Strange gains the Time Stone; opens gateway to multiversal magic.',
  ),
  Entry(
    n: 15,
    saga: 1,
    title: 'Guardians of the Galaxy Vol. 2',
    year: '2017',
    status: Status.important,
    why: 'Explores Peter Quill\'s celestial lineage (Ego) and the team bond.',
    how: 'Expands cosmic scope and sets up Infinity War dynamics.',
  ),
  Entry(
    n: 16,
    saga: 1,
    title: 'Spider-Man: Homecoming',
    year: '2017',
    status: Status.important,
    why: 'Peter Parker\'s growth as a hero under Stark\'s guidance.',
    how: 'Establishes Peter as Tony\'s protege and key future Avenger.',
  ),
  Entry(
    n: 17,
    saga: 1,
    title: 'Thor: Ragnarok',
    year: '2017',
    status: Status.essential,
    why: 'Asgard destroyed; introduces Valkyrie, Korg, and planet Sakaar.',
    how: 'Leads directly into the opening scene of Infinity War.',
  ),
  Entry(
    n: 18,
    saga: 1,
    title: 'Black Panther',
    year: '2018',
    status: Status.essential,
    why: 'Introduces Wakanda, T\'Challa, and Vibranium technology.',
    how: 'Wakanda becomes the primary defense ground against Thanos.',
  ),
  Entry(
    n: 19,
    saga: 1,
    title: 'Avengers: Infinity War',
    year: '2018',
    status: Status.essential,
    why: 'The Avengers fight Thanos to stop him collecting all the Stones.',
    how: 'Thanos succeeds, wiping out half of all life in the universe.',
  ),
  Entry(
    n: 20,
    saga: 1,
    title: 'Ant-Man and the Wasp',
    year: '2018',
    status: Status.important,
    why: 'Continues Scott\'s story and introduces Hope as the Wasp.',
    how: 'Post-credits traps Scott in the Quantum Realm during the Snap.',
  ),
  Entry(
    n: 21,
    saga: 1,
    title: 'Captain Marvel',
    year: '2019',
    status: Status.essential,
    why: '1990s origin story of Carol Danvers and Nick Fury\'s initiative.',
    how: 'Establishes cosmic hero crucial to turning the tide in Endgame.',
  ),
  Entry(
    n: 22,
    saga: 1,
    title: 'Avengers: Endgame',
    year: '2019',
    status: Status.essential,
    why: 'The climax of the Infinity Saga; the Time Heist to defeat Thanos.',
    how: 'Heroes reverse the snap, resetting the universe and closing Phase 3.',
  ),
  Entry(
    n: 23,
    saga: 1,
    title: 'Spider-Man: Far From Home',
    year: '2019',
    status: Status.important,
    why: 'Peter copes with Tony\'s death and faces Mysterio\'s trickery.',
    how: 'First teases the Multiverse concept; ends with Peter exposed.',
  ),
  Entry(
    n: 24,
    saga: 2,
    title: 'WandaVision',
    tag: 'Series',
    year: '2021',
    status: Status.important,
    why: 'Explores Wanda\'s grief, hex reality, and transformation into Scarlet Witch.',
    how: 'Wanda obtains the Darkhold, triggering Multiverse of Madness.',
  ),
  Entry(
    n: 25,
    saga: 2,
    title: 'The Falcon & Winter Soldier',
    tag: 'Series',
    year: '2021',
    status: Status.important,
    why: 'Sam Wilson grapples with shield legacy and geopolitical tension.',
    how: 'Sam officially becomes Captain America; sets up Brave New World.',
  ),
  Entry(
    n: 26,
    saga: 2,
    title: 'Loki',
    tag: 'Seasons 1 & 2',
    year: '2021–23',
    status: Status.essential,
    why: 'Introduces the TVA, Sacred Timeline, Variants, and the multiversal tree.',
    how: 'Officially unlocks the Multiverse rules essential for Doomsday.',
  ),
  Entry(
    n: 27,
    saga: 2,
    title: 'Black Widow',
    year: '2021',
    status: Status.important,
    why: 'Natasha\'s past, the Red Room, and the introduction of Yelena Belova.',
    how: 'Passes the mantle to Yelena, setting up Thunderbolts*.',
  ),
  Entry(
    n: 28,
    saga: 2,
    title: 'Shang-Chi & the Ten Rings',
    year: '2021',
    status: Status.important,
    why: 'Introduces Shang-Chi, the Ta Lo realm, and ancient Ten Rings artifacts.',
    how: 'The Ten Rings beacon signals ancient multiversal power.',
  ),
  Entry(
    n: 29,
    saga: 2,
    title: 'Eternals',
    year: '2021',
    status: Status.important,
    why: 'Introduces the immortal Eternals, Celestials, and Earth\'s true creation.',
    how: 'Leaves the giant dead Celestial Tiamut in the ocean (Adamantium source).',
  ),
  Entry(
    n: 30,
    saga: 2,
    title: 'X-Men / Logan',
    tag: 'Fox Universe',
    year: '2000–17',
    status: Status.requiredUniverse,
    why: 'Original Mutant timelines, Charles Xavier, and Wolverine\'s journey.',
    how: 'Establishes Fox Universe characters returning in the Multiverse Saga.',
  ),
  Entry(
    n: 31,
    saga: 2,
    title: 'Spider-Man: No Way Home',
    year: '2021',
    status: Status.essential,
    why: 'The multiverse spell breaks; brings Tobey, Andrew, and legacy villains.',
    how: 'Proves cross-universe travel and resets Peter\'s identity.',
  ),
  Entry(
    n: 32,
    saga: 2,
    title: 'Doctor Strange in the Multiverse of Madness',
    year: '2022',
    status: Status.essential,
    why: 'Strange travels alternate dimensions with America Chavez.',
    how: 'Introduces Incursions (universe collisions) key to Doomsday.',
  ),
  Entry(
    n: 33,
    saga: 2,
    title: 'Ms. Marvel',
    tag: 'Series',
    year: '2022',
    status: Status.important,
    why: 'Kamala Khan origin; reveals her mutant gene and quantum bangle.',
    how: 'Connects to The Marvels and Young Avengers setup.',
  ),
  Entry(
    n: 34,
    saga: 2,
    title: 'Thor: Love and Thunder',
    year: '2022',
    status: Status.important,
    why: 'Thor faces Gorr the God Butcher; Jane Foster becomes Mighty Thor.',
    how: 'Expands pantheon lore and Thor\'s ongoing galactic journey.',
  ),
  Entry(
    n: 35,
    saga: 2,
    title: 'She-Hulk: Attorney at Law',
    tag: 'Series',
    year: '2022',
    status: Status.important,
    why: 'Jennifer Walters\' legal battles and street-level heroics.',
    how: 'Features Daredevil and introduces superhuman legal status.',
  ),
  Entry(
    n: 36,
    saga: 2,
    title: 'Black Panther: Wakanda Forever',
    year: '2022',
    status: Status.essential,
    why: 'Honors T\'Challa; introduces Shuri as Panther and Namor of Talokan.',
    how: 'Shifts international power struggle over global Vibranium.',
  ),
  Entry(
    n: 37,
    saga: 2,
    title: 'Ant-Man and the Wasp: Quantumania',
    year: '2023',
    status: Status.important,
    why: 'Explores the sub-atomic Quantum Realm and multiversal exile concepts.',
    how: 'Deepens the mechanics of non-linear multiversal space.',
  ),
  Entry(
    n: 38,
    saga: 2,
    title: 'Guardians of the Galaxy Vol. 3',
    year: '2023',
    status: Status.important,
    why: 'Conclusion of the original Guardians team and Rocket\'s origin.',
    how: 'Passes team leadership to Rocket for future cosmic events.',
  ),
  Entry(
    n: 39,
    saga: 2,
    title: 'The Marvels',
    year: '2023',
    status: Status.important,
    why: 'Carol, Monica, and Kamala team up via quantum entanglement.',
    how: 'Post-credits opens a rift to the Fox X-Men dimension (Beast).',
  ),
  Entry(
    n: 40,
    saga: 2,
    title: 'Deadpool & Wolverine',
    year: '2024',
    status: Status.essential,
    why: 'Brings Fox Mutants into the TVA ecosystem and MCU timeline.',
    how: 'Major multiversal bridge uniting Mutants and Avengers.',
  ),
  Entry(
    n: 41,
    saga: 2,
    title: 'Agatha All Along',
    tag: 'Series',
    year: '2024',
    status: Status.important,
    why: 'Explores the Witches\' Road, magical lore, and Billy Maximoff (Wiccan).',
    how: 'Sets up the magical faction and supernatural Avengers elements.',
  ),
  Entry(
    n: 42,
    saga: 2,
    title: 'Captain America: Brave New World',
    year: '2025',
    status: Status.essential,
    why: 'Sam Wilson faces global crisis, Red Hulk, and Adamantium conflict.',
    how: 'Establishes the new Captain America leading Earth\'s defenses.',
  ),
  Entry(
    n: 43,
    saga: 2,
    title: 'Daredevil: Born Again',
    tag: 'Series',
    year: '2025',
    status: Status.important,
    why: 'Matt Murdock vs. Mayor Wilson Fisk in high-stakes NYC conflict.',
    how: 'Anchors street-level vigilantes prior to multiversal collapse.',
  ),
  Entry(
    n: 44,
    saga: 2,
    title: 'The Fantastic Four: First Steps',
    year: '2025',
    status: Status.essential,
    why: 'Origin of Marvel\'s First Family in a retro 1960s universe.',
    how: 'Directly introduces Doctor Doom and the alternate dimension bridge.',
  ),
  Entry(
    n: 45,
    saga: 2,
    title: 'Thunderbolts*',
    year: '2025',
    status: Status.essential,
    why: 'Anti-heroes (Yelena, Bucky, U.S. Agent) unite for dark ops.',
    how: 'Forms a government-backed team in the main timeline.',
  ),
  Entry(
    n: 46,
    saga: 2,
    title: 'Spider-Man: Brand New Day',
    year: '2026',
    status: Status.essential,
    why: 'A grounded Peter Parker in a world where no one remembers him.',
    how: 'Positions Spider-Man on the doorstep of the Doomsday crisis.',
  ),
  Entry(
    n: 47,
    saga: 2,
    title: 'Avengers: Doomsday',
    year: '2026',
    status: Status.upcoming,
    why: 'Doctor Doom threatens all realities across the collapsing Multiverse.',
    how: 'The culmination event. All timelines and heroes collide.',
  ),
];
